sudo: required

language: node_js

node_js:
  - "7.5"

services:
  - docker

before_install:
  - docker pull mysql
  - docker run --name mysql -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=hashiru -d mysql
  - docker ps -a
  - mysql -u root -p secret test < ./test/mysql/data.sql