language: node_js

notifications:
  slack: generaptr:WVInkDTeAegbpm2wBcMmCKv2

node_js:
  - "7.5"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - mysql -u root test < ./test/mysql/data.sql